language: node_js

node_js:
  - "6"

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rvm install 2.4.0
  - gem install scss_lint

script:
  - npm run lint
  - npm run build

notifications:
  slack: hope-ua:eSKEvYMpz0KTwl2G1uGI0qmA
